### ISSUE TITLE
Client-side code improvements [Yozh-todo-list]

### ISSUE THREAD

**Issue by justheuristic** [bigscience-workshop/petals#16]
### Important stuff

- [ ] optimal (instead of random) routing in RemoteSequenceManager
- [x] fault tolerance in RemoteSequentialInferenceSession
- [x] quick slicing with RemoteSequential[5:15] ( @TimDettmers )
- [x] BloomForCausalLM.generate ( @artek0chumak )
- [x] remove lm_head WEIGHT from checkpoint and/or model, convert BloomModel instead (to save 2x client RAM) [@dbaranchuk did it]

### Minor stuff
This list contains all the things i've delegated to future me. They are typically too obscure for anyone else to worry about

- [x] fault tolerance inside RemoteTransformerBlock (as opposed to RemoteSequential)

- [x] in SequenceInfo, keep block_infos as TimedStorage instead of just RemoteSequenceInfo for automatic removal of expired servers
- [x] make RemoteSequential print the state of the model ( @TimDettmers )
- [x] less frequent DHT lookups in RemoteSequenceInfo
- [x] change BloomForCausalLM.forward to call RemoteSequential instead of working layer-by-layer (why: to allow chaining subsequent blocks efficiently)

Note from #45  by @borzunov 

Please consider running a loop instead, maybe using just --num_blocks without explicit --block_indices. If it gets more complicated than just repeating something N times, please move it to a Python script.

**Comment by justheuristic** [comment]
As of 2022.01.02, everything except smart routing has been implemented. Smart routing is currently in progress (see #12 ).
